/**
 * Financial Types
 * 
 * Type definitions for transactions, expenses, and financial analytics.
 */

/**
 * Transaction types
 */
export type TransactionType = 'income' | 'expense' | 'transfer' | 'adjustment';

/**
 * Transaction categories for income
 */
export type IncomeCategory =
  | 'sales'
  | 'services'
  | 'rental'
  | 'investment'
  | 'refund'
  | 'grant'
  | 'other';

/**
 * Transaction categories for expenses
 */
export type ExpenseCategory =
  | 'purchase'
  | 'maintenance'
  | 'supplies'
  | 'utilities'
  | 'rent'
  | 'salaries'
  | 'insurance'
  | 'marketing'
  | 'travel'
  | 'professional_services'
  | 'taxes'
  | 'depreciation'
  | 'other';

/**
 * Payment methods
 */
export type PaymentMethod =
  | 'cash'
  | 'check'
  | 'credit_card'
  | 'debit_card'
  | 'bank_transfer'
  | 'paypal'
  | 'other';

/**
 * Transaction interface
 * Represents a financial transaction (income or expense)
 */
export interface Transaction {
  id: string;
  organization_id: string;
  type: TransactionType;
  category: IncomeCategory | ExpenseCategory;
  amount: number;
  currency: string;
  transaction_date: string;
  description: string;
  reference_number: string | null;
  payment_method: PaymentMethod | null;
  
  // Related entities (optional)
  asset_id: string | null;
  client_id: string | null;
  invoice_id: string | null;
  
  // Metadata
  notes: string | null;
  tags: string[] | null;
  receipt_url: string | null;
  
  // Audit fields
  created_by: string;
  created_at: string;
  updated_at: string;
}

/**
 * Create transaction input
 * Omits auto-generated fields
 */
export type CreateTransactionInput = Omit<
  Transaction,
  'id' | 'organization_id' | 'created_at' | 'updated_at'
>;

/**
 * Update transaction input
 * Partial of create input
 */
export type UpdateTransactionInput = Partial<CreateTransactionInput>;

/**
 * Expense interface
 * Represents a business expense
 */
export interface Expense {
  id: string;
  organization_id: string;
  category: ExpenseCategory;
  amount: number;
  currency: string;
  expense_date: string;
  vendor: string;
  description: string;
  reference_number: string | null;
  payment_method: PaymentMethod | null;
  
  // Related entities (optional)
  asset_id: string | null;
  project_id: string | null;
  
  // Tax and accounting
  is_tax_deductible: boolean;
  is_recurring: boolean;
  recurring_frequency: 'monthly' | 'quarterly' | 'yearly' | null;
  
  // Approval workflow
  status: 'pending' | 'approved' | 'rejected' | 'paid';
  approved_by: string | null;
  approved_at: string | null;
  
  // Metadata
  notes: string | null;
  tags: string[] | null;
  receipt_url: string | null;
  
  // Audit fields
  created_by: string;
  created_at: string;
  updated_at: string;
}

/**
 * Create expense input
 * Omits auto-generated fields
 */
export type CreateExpenseInput = Omit<
  Expense,
  'id' | 'organization_id' | 'created_at' | 'updated_at'
>;

/**
 * Update expense input
 * Partial of create input
 */
export type UpdateExpenseInput = Partial<CreateExpenseInput>;

/**
 * Asset Financials interface
 * Aggregated financial data for a specific asset
 */
export interface AssetFinancials {
  asset_id: string;
  asset_name: string;
  
  // Financial metrics
  total_spend: number;      // Total expenses for this asset
  total_revenue: number;    // Total income generated by this asset
  profit_loss: number;      // Net profit/loss (revenue - spend)
  roi_percentage: number;   // Return on investment percentage
  
  // Optional detailed breakdown
  purchase_cost?: number;
  maintenance_cost?: number;
  operating_cost?: number;
  depreciation?: number;
  current_value?: number;
  
  // Time period (optional, for filtered reports)
  period_start?: string;
  period_end?: string;
  
  // Metadata
  currency: string;
  last_updated: string;
}

/**
 * Monthly Profit & Loss interface
 * Monthly aggregated financial data
 */
export interface MonthlyPL {
  month: string;              // Format: YYYY-MM (e.g., "2024-10")
  total_revenue: number;      // Total income for the month
  total_expenses: number;     // Total expenses for the month
  net_profit: number;         // Net profit/loss (revenue - expenses)
  
  // Optional detailed breakdown
  revenue_by_category?: Record<IncomeCategory, number>;
  expenses_by_category?: Record<ExpenseCategory, number>;
  
  // Asset-related financials
  asset_count?: number;       // Number of assets
  asset_purchases?: number;   // Money spent on new assets
  asset_sales?: number;       // Revenue from asset sales
  
  // Invoice-related financials
  invoices_sent?: number;     // Number of invoices sent
  invoices_paid?: number;     // Number of invoices paid
  outstanding_balance?: number; // Total outstanding invoice balance
  
  // Metadata
  currency: string;
  transactions_count?: number;
}

/**
 * Yearly Profit & Loss interface
 * Yearly aggregated financial data
 */
export interface YearlyPL {
  year: string;               // Format: YYYY (e.g., "2024")
  total_revenue: number;
  total_expenses: number;
  net_profit: number;
  
  // Quarterly breakdown (optional)
  quarters?: {
    Q1: MonthlyPL;
    Q2: MonthlyPL;
    Q3: MonthlyPL;
    Q4: MonthlyPL;
  };
  
  // Monthly breakdown (optional)
  months?: MonthlyPL[];
  
  // Year-over-year comparison (optional)
  yoy_revenue_growth?: number;      // Percentage
  yoy_expense_growth?: number;      // Percentage
  yoy_profit_growth?: number;       // Percentage
  
  // Metadata
  currency: string;
}

/**
 * Financial Summary interface
 * High-level financial overview
 */
export interface FinancialSummary {
  organization_id: string;
  
  // Current period (e.g., current month)
  current_period: {
    revenue: number;
    expenses: number;
    profit: number;
  };
  
  // Previous period comparison
  previous_period: {
    revenue: number;
    expenses: number;
    profit: number;
  };
  
  // Growth rates
  revenue_growth: number;       // Percentage
  expense_growth: number;       // Percentage
  profit_growth: number;        // Percentage
  
  // Year-to-date
  ytd: {
    revenue: number;
    expenses: number;
    profit: number;
  };
  
  // All-time totals
  all_time: {
    total_revenue: number;
    total_expenses: number;
    total_profit: number;
  };
  
  // Assets
  assets: {
    total_value: number;
    total_count: number;
    total_investment: number;
  };
  
  // Invoices
  invoices: {
    total_outstanding: number;
    total_overdue: number;
    total_paid_this_month: number;
  };
  
  // Metadata
  currency: string;
  last_updated: string;
}

/**
 * Date range filter
 */
export interface DateRangeFilter {
  start_date: string;
  end_date: string;
}

/**
 * Financial report filters
 */
export interface FinancialReportFilters {
  date_range?: DateRangeFilter;
  asset_ids?: string[];
  client_ids?: string[];
  categories?: (IncomeCategory | ExpenseCategory)[];
  transaction_types?: TransactionType[];
  payment_methods?: PaymentMethod[];
  min_amount?: number;
  max_amount?: number;
}

